# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
    - linux

julia:
    - 1.6
    - nightly

coveralls: true

matrix:
  allow_failures:
    - julia: nightly

jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip

script:
  - julia --project --color=yes -e 'using Pkg; Pkg.build(; verbose=true); Pkg.test("FeedbackNets"; coverage=true)'

after_success:
  - julia --project -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
